apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-catalog-publish-pipeline
timeout: 30m
spec:
  params:
    - name: apikey
      description: ibm cloud api key
    - name: repository
      description: git repository url
      default: https://github.com/kubeflow/kfp-tekton
    - name: branch
      description: repository branch
      default: master
    - name: directory-name
      description: Directory to clone repository into
      default: kfp-tekton
    - name: registry-region
      description: The IBM Cloud region for image registry
      default: ibm:yp:us-south
    - name: registry-namespace
      description: Container registry namespace
    - name: dev-region
      default: us-south
    - name: dev-resource-group
      default: default
    - name: dev-org
      description: organization
      default: dev-advo
    - name: dev-space
      description: space
      default: dev
    - name: cluster-name
      description: the name of the cluster to target
      default: iks-cluster
    - name: tekton-version
      description: tekton version
      default: "previous/v0.21.0"
    - name: tekton-ns
      description: tekton namespace
      default: "tekton-pipelines"
    - name: push-to-dockerhub
      description: flag to signal if images should be pushed to dockerhub
      default: '0'
    - name: dockerhub-username
      description: Dockerhub username
      default: kfptektonbot
    - name: docker-namespace
      description: Image namespace
      default: aipipeline
    - name: image-tag
      description: Tag for all images pushed to dockerhub/ibmcloud
      default: nightly
    - name: pipeline-debug
      description: Flag used by tekton-catalog tasks
      default: '0'
    # kubectl-wrapper specific parameters
    - name: path-to-kubectl-wrapper-context
      description: >-
        Path to kubectl-wrapper docker build directory.
      default: tekton-catalog/kubectl-wrapper
    - name: path-to-kubectl-wrapper-dockerfile
      description: Path to directory with kubectl-wrapper dockerfile
      default: tekton-catalog/kubectl-wrapper
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
        - name: directory-name
          value: $(params.directory-name)
      workspaces:
        - name: task-pvc
          workspace: pipeline-ws
    # ==========================================================
    # Kubectl Wrapper Tasks
    # ==========================================================
    - name: build-kubectl-wrapper-binaries
      taskRef:
        name: build-binaries
      runAfter:
        - git-clone
      params:
        - name: directory-name
          value: $(params.directory-name)
        - name: build-dir
          value: tekton-catalog/kubectl-wrapper
      workspaces:
        - name: task-pvc
          workspace: pipeline-ws
    - name: containerize-kubectl-wrapper
      runAfter:
        - build-kubectl-wrapper-binaries
      taskRef:
        name: icr-containerize
      params:
        - name: continuous-delivery-context-secret
          value: secure-properties
        - name: container-registry-apikey-secret-key
          value: apikey
        - name: registry-region
          value: $(params.registry-region)
        - name: registry-namespace
          value: $(params.registry-namespace)
        - name: image-name
          value: "kubeclient"
        - name: path-to-context
          value: $(params.directory-name)/$(params.path-to-kubectl-wrapper-context)
        - name: path-to-dockerfile
          value: $(params.directory-name)/$(params.path-to-kubectl-wrapper-dockerfile)
        - name: additional-tags-script
          value: >
            IMAGE_TAG=$(tasks.git-clone.results.image-tag)

            echo "$IMAGE_TAG"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: source
          workspace: pipeline-ws
    - name: setup-kubectl-wrapper-deploy
      taskRef:
        name: setup-kubectl-wrapper-deploy
      runAfter:
        - containerize-kubectl-wrapper
      params:
        - name: kubectl-wrapper-image-url
          value: $(tasks.containerize-kubectl-wrapper.results.image-repository)
        - name: image-tag
          value: $(tasks.git-clone.results.image-tag)
      workspaces:
        - name: task-pvc
          workspace: pipeline-ws
    - name: deploy-tekton
      taskRef:
        name: deploy-tekton
      runAfter:
        - setup-kubectl-wrapper-deploy
      params:
        - name: directory-name
          value: $(params.directory-name)
        - name: apikey
          value: $(params.apikey)
        - name: docker-username
          value: iamapikey
        - name: docker-password
          value: $(params.apikey)
        - name: kubernetes-cluster
          value: $(params.cluster-name)
        - name: tekton-version
          value: $(params.tekton-version)
        - name: tekton-ns
          value: $(params.tekton-ns)
        - name: region
          value: $(params.dev-region)
        - name: org
          value: $(params.dev-org)
        - name: space
          value: $(params.dev-space)
        - name: resource-group
          value: $(params.dev-resource-group)
      workspaces:
        - name: task-pvc
          workspace: pipeline-ws
    - name: deploy-kubectl-wrapper-e2e
      taskRef:
        name: iks-deploy-to-kubernetes
      runAfter:
        - deploy-tekton
      retries: 1
      params:
        - name: continuous-delivery-context-secret
          value: secure-properties
        - name: kubernetes-service-apikey-secret-key
          value: apikey
        - name: cluster-region
          value: $(params.dev-region)
        - name: resource-group
          value: $(params.dev-resource-group)
        - name: cluster-name
          value: $(params.cluster-name)
        - name: script
          value: |
            #!/bin/bash
            set -euxo pipefail
            cd $(params.directory-name)
            source scripts/deploy/iks/tekton-catalog/deploy-kubectl-wrapper-e2e.sh
            APP_URL="null"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
    - name: publish-kubectl-wrapper-image-to-dockerhub
      taskRef:
        name: publish-images-to-dockerhub
      runAfter:
        - deploy-kubectl-wrapper-e2e
      when:
        - input: $(params.push-to-dockerhub)
          operator: in
          values:
            - '1'
      params:
        - name: continuous-delivery-context-secret
          value: secure-properties
        - name: kubernetes-service-apikey-secret-key
          value: apikey
        - name: dockerhub-token-secret-key
          value: dockerhub-token
        - name: cluster-region
          value: $(params.dev-region)
        - name: resource-group
          value: $(params.dev-resource-group)
        - name: cluster-name
          value: $(params.cluster-name)
        - name: directory-name
          value: $(params.directory-name)
        - name: dockerhub-username
          value: $(params.dockerhub-username)
        - name: docker-namespace
          value: $(params.docker-namespace)
        - name: image-tag
          value: $(params.image-tag)
        - name: publish-script
          value: scripts/deploy/iks/tekton-catalog/publish-kubectl-wrapper-image.sh
      workspaces:
        - name: task-pvc
          workspace: pipeline-ws
  # ==========================================================
  # Final Task
  # ==========================================================
  finally:
    - name: cleanup
      taskRef:
        Name: cleanup
      params:
        - name: continuous-delivery-context-secret
          value: secure-properties
        - name: kubernetes-service-apikey-secret-key
          value: apikey
        - name: cluster-region
          value: $(params.dev-region)
        - name: resource-group
          value: $(params.dev-resource-group)
        - name: cluster-name
          value: $(params.cluster-name)
        - name: directory-name
          value: $(params.directory-name)
        - name: org
          value: $(params.dev-org)
        - name: space
          value: $(params.dev-space)
        - name: resource-group
          value: $(params.dev-resource-group)
      workspaces:
        - name: task-pvc
          workspace: pipeline-ws
